### ISSUE TITLE
Access to the project

### ISSUE THREAD

**Issue by TomaszGabrysiak** [kq333/Messanger#1]
Hi,

Could you please add my colleagues to the project so they can also take a look?
Nicknames: @FenNek55, @barchuckie, and @patrykkurzeja91.

Also, please let me know if the task is finished and ready to check out.

Thanks a lot!

**Comment by kq333** [comment]
I already did.

**Comment by TomaszGabrysiak** [comment]
Thanks! We'll check it out, please expect the feedback soon.
